export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_TOKEN = 'SET_TOKEN';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';

export const ADVERT_LOADED_REQUEST = 'ADVERT_LOADED_REQUEST';
export const ADVERT_LOADED_SUCCESS = 'ADVERT_LOADED_SUCCESS';
export const ADVERT_LOADED_FAILURE = 'ADVERT_LOADED_FAILURE';

export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';
export const ADVERT_CREATED_REQUEST = 'ADVERT_CREATED_REQUEST';
export const ADVERT_CREATED_FAILURE = 'ADVERT_CREATED_FAILURE';

export const ADVERT_DELETED_SUCCESS = 'ADVERT_DELETED_SUCCESS';
export const ADVERT_DELETED_REQUEST = 'ADVERT_DELETED_REQUEST';
export const ADVERT_DELETED_FAILURE = 'ADVERT_DELETED_FAILURE';

export const ADD_TAGS_REQUEST = 'ADD_TAGS_REQUEST';
export const ADD_TAGS_SUCCESS = 'ADD_TAGS_SUCCESS';
export const ADD_TAGS_FAILURE = 'ADD_TAGS_FAILURE';

export const ADV_FILTER_NAME = 'ADV_FILTER_NAME';
export const ADV_FILTER_SALE = 'ADV_FILTER_SALE';
export const ADV_FILTER_TAGS = 'ADV_FILTER_TAGS';
//export const ADV_FILTER_MIN_PRICE = 'ADV_FILTER_MIN_PRICE';
//export const ADV_FILTER_MAX_PRICE = 'ADV_FILTER_MAX_PRICE';
export const ADV_FILTER_PRICE = 'ADV_FILTER_PRICE';

export const TOGGLE_RESULT = 'TOGGLE_RESULT'; //Show filter results?
